#!/bin/bash
set -e
set -o pipefail

pnpm i -D \
  @ionic/core@5.0.5 \
  @stencil/core@~1.8.8

npm run build
surge www https://ionic-input-demo-work.surge.sh

pnpm i -D \
  @ionic/core@5.0.6 \
  @stencil/core@~1.8.8

npm run build
surge www https://ionic-input-demo-not-work.surge.sh
